type:build:
  - ".github/**"
  - ".coveralls.yml"
  - "phpunit.github.xml"
  - ".gitignore"
  - "ecs.yml"
  - "composer.json"
  - "composer.lock"

type:jobs:
  - "src/Jobs/*"

type:stores:
  - "src/Stores/**/*"

type:facades:
  - "src/Facades/*"

type:exceptions:
  - "src/Exceptions/*"

type:decorators:
  - "src/Decorators/*"

type:tests:
  - any: ['tests/**/*', 'phpunit.xml.dist', 'tests.sh']

theme:docs:
  - "README.md"
  - "LICENSE"
  - "CONTRIBUTING.md"
  - "CODE_OF_CONDUCT.md"
